### PR TITLE
Added splitting of input text by various punctuation

### LINKED ISSUE #52: Add non-standard punctuation to vocal synthesis

### PR DESCRIPTION
**Pull request by JacobSmith1020**
Can now split by ., ?, !, ;, :, —, and ...

I reworked how the text is passed to the synthesizer. Instead of a span to determine where breaks are in the generated speech, the same effect can be achieved by appending extra space characters after terminating punctuation. This creates pauses that are much more configurable in their length, compared to the pauses generated from appending synthesized speech segments to one another which felt a bit long and inconsistent. I think this flows better than the span method personally, let me know what you guys think.

Input text = "It began with the forging of the great rings. Three were given to the elves, immortal, wisest, and fairest of all beings! Seven to the dwarf lords, great miners and craftsmen of the mountain halls? And nine, nine rings were gifted to the race of men — who above all else, desired power... For within these rings was bound the strength and will to govern each race; "

Punctuation regex = '\. |\? |\! |\; |\: | \— |\—|\.\.\. |\.|\?|\!|\;|\:|\.\.\.'

Split text = ['It began with the forging of the great rings', 'Three were given to the elves, immortal, wisest, and fairest of all beings', 'Seven to the dwarf lords, great miners and craftsmen of the mountain halls', 'And nine, nine rings were gifted to the race of men', 'who above all else, desired power', 'For within these rings was bound the strength and will to govern each race']

Text passed to the synthesizer = 'It began with the forging of the great rings.   Three were given to the elves, immortal, wisest, and fairest of all beings!   Seven to the dwarf lords, great miners and craftsmen of the mountain halls?   And nine, nine rings were gifted to the race of men —     who above all else, desired power...   For within these rings was bound the strength and will to govern each race;   '

Additionally, synthesizing sentences separately and then combining them is significantly slower than synthesizing one string of all sentences.

### CODE REVIEW

**Comment by andrew-fennell** [comment]
Can you clarify if this is working properly?

```text```: "In many areas, people and local governments do not sustainably use their natural resources. Mining for natural gases, deforestation, and even improper use of water resources can have tremendous effects on the environment. While these strategies often attempt to boost local economies, their effects can lead to oil spills, interrupted animal habitats, and droughts."

```input_subs```: ['In many areas, people and local governments do not sustainably use their natural resources.   Mining for natural gases, deforestation, and even improper use of water resources can have tremendous effects on the environment.   While 
these strategies often attempt to boost local economies, their effects can lead to oil spills, interrupted animal habitats, and droughts.'

I'm not convinced the extra spaces is causing the synthesized voice to pause.

**Comment by andrew-fennell** [comment]
I think the punctuation regex that you have implemented is far superior to the span that we had previously. I just want to make sure that the flow is being effected by the modifications to the input text.

**Comment by JacobSmith1020** [comment]
EDIT: The synthesizer is now passed each sentence individually to synthesize. The silence from the end of the synthesis is trimmed with pydub and all sentences are concatenated together at the end. Silence trimming is defined by ```silence_to_cut = 600 #measured in ms```. Regex is unchanged from above.

**Comment by JacobSmith1020** [comment]
Sample output: https://drive.google.com/file/d/14_fQ52R7fEXjET0GHP67y3HfenwYETP8/view?usp=sharing

**Comment by andrew-fennell** [comment]
> Sample output: https://drive.google.com/file/d/14_fQ52R7fEXjET0GHP67y3HfenwYETP8/view?usp=sharing

This sounds much more natural than anything we have previously had. 

I'm going to look through the code and test locally again. As far as the synthesis quality, this is ready to go!

**Review by andrew-fennell — APPROVED** [review]
LGTM. Great work on this issue.

**Pull request merged**
