### PR TITLE
Integrate master's thesis into repository

### PR DESCRIPTION
**Pull request by JacobSmith1020**
Added master's thesis under cognative>backend>real-time-voice-cloning. Added packages to requirements.txt to reflect what is needed for the master's thesis to function. Added git large file storage (lfs) to .gitattributes to support pushing and uploading oversized *.pt files (cognative>backend>real-time-voice-cloning>saved_models>default).

Related issues: #19

### CODE REVIEW

**Review by ctis98 — DISMISSED** [review]
LGTM

**Comment by andrew-fennell** [comment]
Add some credits to our main README for the master's thesis creator and link his project, since his project will serve as a starting point for a crucial component of our project.

**Review by andrew-fennell — CHANGES_REQUESTED** [review]
Add some credits to our main README for the master's thesis creator and link his project, since his project will serve as a starting point for a crucial component of our project.

**Review by andrew-fennell — APPROVED** [review]
:)

**Pull request merged**
