### PR TITLE
Added Swedish support; Added UI drop-downs; Adjusted main.py to support dest_lang

### LINKED ISSUE #43: Finalize Pre-User Testing cross-language models
Finalize all cross-language models that will be used for user testing.

**Add documentation for all supported models.**

### LINKED ISSUE #86: Add text file input capability
Dialogue added as a .txt file would be a good improvement.

### LINKED ISSUE #89: Users should not be able to type their own extension in UI (default to .wav or .mp3)
Discovered in #79 

See here for examples: https://github.com/andrew-fennell/CogNative/pull/79#pullrequestreview-947659429

### PR DESCRIPTION
**Pull request by andrew-fennell**
I'll apologize in advance... This is a huge PR due to the addition of Swedish.

I added Swedish support with the guidance of [this](https://github.com/raccoonML/Real-Time-Voice-Cloning) repo.
The repository used Tensorflow to create a Swedish synthesizer that I believe works remarkably well.

I added support to this project to use this functionality by adding a separate models module: ```RTVCSwedish```. This allows separation between the PyTorch and Tensorflow portions of the project.

I added UI drop-downs, built functionality, and patched all files to include ```RTVCSwedish``` when necessary. I also added ```dest_lang``` as an input (with an optional flag as well) to allow the user to choose between English or Swedish.

#43

### CODE REVIEW

**Review by ctis98 — DISMISSED** [review]
Good Lord that's a lot of files... LGTM

**Comment by andrew-fennell** [comment]
I'm removing Mac OS from testing because the tensorflow modules will change. This can be added back in for a later PR if we modify the program to support Mac OS.

**Comment by andrew-fennell** [comment]
```Python version >= 3.7``` should now work with the program. IF python version is **not equal to** 3.7, ```tensorflow``` will not be pip install with ```requirements.txt``` and swedish will not be supported.

**Comment by JacobSmith1020** [comment]
@andrew-fennell 
Errors i've encountered setting up this branch on windows and how to fix them:

1. pywebrtcvad threw an error when installing through ```pip install -r requirements.txt```. Fixed by manually installing webrtcvad with ```pip install webrtcvad``` (not sure why this fails in the pip requirements).

2. Needed to ```pip install multiprocess```, which seemingly fixed a whole host of unrelated errors.

Additionally, you cannot make successive calls to clone in the UI, it will always tell you that a voice is already being cloned after the first one.

**Review by JacobSmith1020 — APPROVED** [review]
Successfully installed and run locally. Everything is working as it should :)

**Pull request merged**
