### PR TITLE
Language auto-detection

### LINKED ISSUE #44: Add language auto-detection
Add a language auto-detection feature. This should auto-detect the language being spoken in an input audio file (preferably a .wav file).

### PR DESCRIPTION
**Pull request by andrew-fennell**
_Branched off of Jonathan's branch._

Since we switched to ```Google Cloud Engine``` for STT, rather than using the wrapper library ```SpeechRecognition```, some things needed to be changed.

This AUTO-DETECTS the language in a audio file! There is no more language input needed when transcribing audio. There is, however, language input needed on the "to-clone" audio, because the encoder needs to be different. 

This just takes removes the need for a single input.

Closes #44

### CODE REVIEW

**Comment by andrew-fennell** [comment]
I should mention, the additions to the code in this PR are being tested by the ```test_STT``` checks. They are correctly identifying which language to translate to.

**Review by JacobSmith1020 — CHANGES_REQUESTED** [review]
When prompted if audio/text and choosing audio, it will still prompt for the language of the audio even though it isn't needed any longer. Otherwise, audio synthesis works fine. When choosing text input, a "TypeError: module object is not callable" will be thrown for ```tr = translation()```

image

**Comment by andrew-fennell** [comment]
> When choosing text input, a "TypeError: module object is not callable" will be thrown for `tr = translation()`

@JacobSmith1020 Sorry about that. It is fixed now.

So now if you enter text to synthesize in a different (supported) language, it translates it to English and synthesizes the translated text.

**Comment by JacobSmith1020** [comment]
@andrew-fennell when you select audio as the source it still prompts you for the source language (main.py 52-55). Should this still be in here, it appears obsolete to me?

**Comment by andrew-fennell** [comment]
> it appears obsolete to me

Yes! This is obsolete. I think this section came back with the recent merges to main, but this is no longer needed.

**Review by JacobSmith1020 — APPROVED** [review]
Everything looks to be working without issue now :)

**Pull request merged**
