### PR TITLE
Created hardware doc

### LINKED ISSUE #37: Create hardware documentation
Hardware documentation should be created (preferably in .md format).

This documentation can replace the current README.md file at [CogNative/CogNative/hardware](https://github.com/andrew-fennell/CogNative/tree/main/CogNative/hardware). 

Documentation should cover all of the hardware that **we** are using. It should also include anything that someone would need to run this project. (CUDA)

Feel free to set minimum specs in this document for other components, but I don't think it is required.

### PR DESCRIPTION
**Pull request by austin-currington**
Adding HWDOC for automerge

### CODE REVIEW

**Comment by JacobSmith1020** [comment]
What source audio file length did you input when testing the GPU VRAM usage to get 2.2GB? I know that I tested it on a GTX980M with 8GB VRAM and ran out of memory usage on about an hour long wav file, causing CUDA to throw an error. This might be something we should mention in the hardware section if you encountered this problem.

**Comment by andrew-fennell** [comment]
Closes #37

**Comment by austin-currington** [comment]
> What source audio file length did you input when testing the GPU VRAM usage to get 2.2GB? I know that I tested it on a GTX980M with 8GB VRAM and ran out of memory usage on about an hour long wav file, causing CUDA to throw an error. This might be something we should mention in the hardware section if you encountered this problem.

MatthewM66.wav; I updated readme to reflect this as we discussed verbally.

**Review by JacobSmith1020 — DISMISSED** [review]
Looks good.

**Review by andrew-fennell — APPROVED** [review]

**Pull request merged**
