### PR TITLE
Integrates STT and translation into main.py

### LINKED ISSUE #41: Integrate speech_recognition module with vocal synthesis models.
Create a module that will handle all vocal synthesis interaction. 

This should include:
- Taking in audio file path
- Choosing language (or auto identifying language, when that is added)
- Transcribing the audio file (in any supported language)
- Translating the audio file (to any supported language)
- Synthesizing audio in that language, that mimics the the source voice
- Handling the output location of those files

The output audio may be **bad** before an improved model is implemented for cross-language vocal synthesis to the destination language. **This is okay.** The point is to add a module that will handle all of these top-level things.

We will narrow the scope to specific source and destination languages that are supported by our vocal synthesis models when we begin creating those models.

### PR DESCRIPTION
**Pull request by andrew-fennell**
Closes #41

### CODE REVIEW

**Review by JacobSmith1020 — DISMISSED** [review]
Will crash if you capitalize the language of audio file when prompted (Should the language auto detection be added here?). Might want to specify to replace the credentials.json.template file or remove the .template extension if they try to edit the file instead. Other functionality works without error locally. It seems this PR67 encompasses everything in PR66 so both are in working order.

**Comment by andrew-fennell** [comment]
> Will crash if you capitalize the language of audio file when prompted

I think we should just do ```<language>.lower()``` on any language input.

**Comment by andrew-fennell** [comment]
@JacobSmith1020 I made those changes (edited README step 7 and made the language inputs lowercase).

**Review by JacobSmith1020 — DISMISSED** [review]
Works great. No discernable issues on my end :)

**Comment by andrew-fennell** [comment]
> Works great.

@JacobSmith1020 I'm sorry I _once again_ dismissed your PR by committing merge conflicts.

Sorry about that.

**Review by JacobSmith1020 — APPROVED** [review]
:)

**Pull request merged**
